"""initial tables

Revision ID: 1fdf1d71af8e
Revises: 
Create Date: 2025-12-31 14:55:18.495374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1fdf1d71af8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'updated_by')
    op.drop_column('project', 'created_by')
    op.drop_column('project', 'deleted_by')
    op.add_column('user_story', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.alter_column('user_story', 'start_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('user_story', 'end_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_story_assignee_id'), 'user_story', ['assignee_id'], unique=False)
    op.create_foreign_key(None, 'user_story', 'users', ['assignee_id'], ['id'])
    op.drop_column('user_story', 'created_by')
    op.drop_column('user_story', 'updated_by')
    op.drop_column('user_story', 'deleted_by')
    op.drop_column('user_story', 'closed_at')
    op.drop_column('user_story', 'profile_pic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_story', sa.Column('profile_pic', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user_story', sa.Column('closed_at', mysql.TIMESTAMP(), nullable=True))
    op.add_column('user_story', sa.Column('deleted_by', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user_story', sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user_story', sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'user_story', type_='foreignkey')
    op.drop_index(op.f('ix_user_story_assignee_id'), table_name='user_story')
    op.alter_column('user_story', 'end_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('user_story', 'start_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.drop_column('user_story', 'assignee_id')
    op.add_column('project', sa.Column('deleted_by', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('project', sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('project', sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
