"""initial tables

Revision ID: ae930d5839d7
Revises: 
Create Date: 2025-12-31 18:21:12.700947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae930d5839d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_column('project', 'created_by')
    op.drop_column('project', 'deleted_by')
    op.drop_column('project', 'updated_by')
    op.add_column('user_story', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('user_story', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('user_story', sa.Column('end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_user_story_assignee_id'), 'user_story', ['assignee_id'], unique=False)
    op.create_foreign_key(None, 'user_story', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_story', type_='foreignkey')
    op.drop_index(op.f('ix_user_story_assignee_id'), table_name='user_story')
    op.drop_column('user_story', 'end_date')
    op.drop_column('user_story', 'start_date')
    op.drop_column('user_story', 'assignee_id')
    op.add_column('project', sa.Column('updated_by', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('project', sa.Column('deleted_by', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('project', sa.Column('created_by', mysql.VARCHAR(length=255), nullable=True))
    op.create_table('projects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('project_prefix', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('increment_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
